/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    navigation: Navigation;
    themes: Theme;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en' | 'es') | ('fr' | 'en' | 'es')[];
  globals: {
    'legal-notice': LegalNotice;
    confidentiality: Confidentiality;
    cgv: Cgv;
    customization: Customization;
  };
  globalsSelect: {
    'legal-notice': LegalNoticeSelect<false> | LegalNoticeSelect<true>;
    confidentiality: ConfidentialitySelect<false> | ConfidentialitySelect<true>;
    cgv: CgvSelect<false> | CgvSelect<true>;
    customization: CustomizationSelect<false> | CustomizationSelect<true>;
  };
  locale: 'fr' | 'en' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'author' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    layout?:
      | (
          | {
              contentLayout: (
                | {
                    textBlockField: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'textBlock';
                  }
                | {
                    imageBlockField: number | Media;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'imageBlock';
                  }
                | {
                    buttonsListField?:
                      | {
                          type: 'page' | 'post' | 'external';
                          page?: (number | null) | Page;
                          post?: (number | null) | Post;
                          label?: string | null;
                          url?: string | null;
                          image?: (number | null) | Media;
                          newTab?: boolean | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'buttonsListBlock';
                  }
              )[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'text-intro';
            }
          | {
              contentLayout: (
                | {
                    textBlockField: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'textBlock';
                  }
                | {
                    imageBlockField: number | Media;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'imageBlock';
                  }
                | {
                    buttonsListField?:
                      | {
                          type: 'page' | 'post' | 'external';
                          page?: (number | null) | Page;
                          post?: (number | null) | Post;
                          label?: string | null;
                          url?: string | null;
                          image?: (number | null) | Media;
                          newTab?: boolean | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'buttonsListBlock';
                  }
              )[];
              image: number | Media;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text-image';
            }
          | {
              contentLayout: (
                | {
                    textBlockField: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'textBlock';
                  }
                | {
                    imageBlockField: number | Media;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'imageBlock';
                  }
                | {
                    buttonsListField?:
                      | {
                          type: 'page' | 'post' | 'external';
                          page?: (number | null) | Page;
                          post?: (number | null) | Post;
                          label?: string | null;
                          url?: string | null;
                          image?: (number | null) | Media;
                          newTab?: boolean | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'buttonsListBlock';
                  }
              )[];
              image1: number | Media;
              image2?: (number | null) | Media;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text-double-image';
            }
          | {
              hero_image: (number | Media)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'heroscreen';
            }
          | {
              parallax_image: number | Media;
              parallax_speed: number;
              id?: string | null;
              blockName?: string | null;
              blockType: 'parallax';
            }
          | {
              htmlCode: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'html-content';
            }
        )[]
      | null;
  };
  config?: {
    published?: ('0' | '1') | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?:
    | (
        | {
            contentLayout: (
              | {
                  textBlockField: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textBlock';
                }
              | {
                  imageBlockField: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'imageBlock';
                }
              | {
                  buttonsListField?:
                    | {
                        type: 'page' | 'post' | 'external';
                        page?: (number | null) | Page;
                        post?: (number | null) | Post;
                        label?: string | null;
                        url?: string | null;
                        image?: (number | null) | Media;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'buttonsListBlock';
                }
            )[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-intro';
          }
        | {
            contentLayout: (
              | {
                  textBlockField: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textBlock';
                }
              | {
                  imageBlockField: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'imageBlock';
                }
              | {
                  buttonsListField?:
                    | {
                        type: 'page' | 'post' | 'external';
                        page?: (number | null) | Page;
                        post?: (number | null) | Post;
                        label?: string | null;
                        url?: string | null;
                        image?: (number | null) | Media;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'buttonsListBlock';
                }
            )[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            contentLayout: (
              | {
                  textBlockField: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textBlock';
                }
              | {
                  imageBlockField: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'imageBlock';
                }
              | {
                  buttonsListField?:
                    | {
                        type: 'page' | 'post' | 'external';
                        page?: (number | null) | Page;
                        post?: (number | null) | Post;
                        label?: string | null;
                        url?: string | null;
                        image?: (number | null) | Media;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'buttonsListBlock';
                }
            )[];
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-image';
          }
        | {
            contentLayout: (
              | {
                  textBlockField: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textBlock';
                }
              | {
                  imageBlockField: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'imageBlock';
                }
              | {
                  buttonsListField?:
                    | {
                        type: 'page' | 'post' | 'external';
                        page?: (number | null) | Page;
                        post?: (number | null) | Post;
                        label?: string | null;
                        url?: string | null;
                        image?: (number | null) | Media;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'buttonsListBlock';
                }
            )[];
            image1: number | Media;
            image2?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-double-image';
          }
        | {
            hero_image: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroscreen';
          }
        | {
            parallax_image: number | Media;
            parallax_speed: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'parallax';
          }
        | {
            htmlCode: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'html-content';
          }
      )[]
    | null;
  coverImage?: (number | null) | Media;
  config?: {
    published?: ('0' | '1' | '2') | null;
    createdBy?: (number | null) | User;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  menuId: 'main-menu' | 'secondary-menu' | 'footer-menu';
  items?:
    | {
        type: 'page' | 'post' | 'external';
        page?: (number | null) | Page;
        post?: (number | null) | Post;
        label?: string | null;
        url?: string | null;
        image?: (number | null) | Media;
        newTab?: boolean | null;
        children?:
          | {
              type: 'page' | 'post' | 'external';
              page?: (number | null) | Page;
              post?: (number | null) | Post;
              label?: string | null;
              url?: string | null;
              image?: (number | null) | Media;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  themeName: string;
  zip: number | Media;
  themeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  formType: 'contact-form' | 'news-form';
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            label: string;
            placeholder?: string | null;
            min?: number | null;
            max?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            label: string;
            placeholder?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        layout?:
          | T
          | {
              'text-intro'?:
                | T
                | {
                    contentLayout?:
                      | T
                      | {
                          textBlock?:
                            | T
                            | {
                                textBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imageBlock?:
                            | T
                            | {
                                imageBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          buttonsListBlock?:
                            | T
                            | {
                                buttonsListField?:
                                  | T
                                  | {
                                      type?: T;
                                      page?: T;
                                      post?: T;
                                      label?: T;
                                      url?: T;
                                      image?: T;
                                      newTab?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              'text-image'?:
                | T
                | {
                    contentLayout?:
                      | T
                      | {
                          textBlock?:
                            | T
                            | {
                                textBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imageBlock?:
                            | T
                            | {
                                imageBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          buttonsListBlock?:
                            | T
                            | {
                                buttonsListField?:
                                  | T
                                  | {
                                      type?: T;
                                      page?: T;
                                      post?: T;
                                      label?: T;
                                      url?: T;
                                      image?: T;
                                      newTab?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    image?: T;
                    id?: T;
                    blockName?: T;
                  };
              'text-double-image'?:
                | T
                | {
                    contentLayout?:
                      | T
                      | {
                          textBlock?:
                            | T
                            | {
                                textBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imageBlock?:
                            | T
                            | {
                                imageBlockField?: T;
                                id?: T;
                                blockName?: T;
                              };
                          buttonsListBlock?:
                            | T
                            | {
                                buttonsListField?:
                                  | T
                                  | {
                                      type?: T;
                                      page?: T;
                                      post?: T;
                                      label?: T;
                                      url?: T;
                                      image?: T;
                                      newTab?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    image1?: T;
                    image2?: T;
                    id?: T;
                    blockName?: T;
                  };
              heroscreen?:
                | T
                | {
                    hero_image?: T;
                    id?: T;
                    blockName?: T;
                  };
              parallax?:
                | T
                | {
                    parallax_image?: T;
                    parallax_speed?: T;
                    id?: T;
                    blockName?: T;
                  };
              'html-content'?:
                | T
                | {
                    htmlCode?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  config?:
    | T
    | {
        published?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?:
    | T
    | {
        'text-intro'?:
          | T
          | {
              contentLayout?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          textBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          imageBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonsListBlock?:
                      | T
                      | {
                          buttonsListField?:
                            | T
                            | {
                                type?: T;
                                page?: T;
                                post?: T;
                                label?: T;
                                url?: T;
                                image?: T;
                                newTab?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              contentLayout?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          textBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          imageBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonsListBlock?:
                      | T
                      | {
                          buttonsListField?:
                            | T
                            | {
                                type?: T;
                                page?: T;
                                post?: T;
                                label?: T;
                                url?: T;
                                image?: T;
                                newTab?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'text-image'?:
          | T
          | {
              contentLayout?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          textBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          imageBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonsListBlock?:
                      | T
                      | {
                          buttonsListField?:
                            | T
                            | {
                                type?: T;
                                page?: T;
                                post?: T;
                                label?: T;
                                url?: T;
                                image?: T;
                                newTab?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        'text-double-image'?:
          | T
          | {
              contentLayout?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          textBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          imageBlockField?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonsListBlock?:
                      | T
                      | {
                          buttonsListField?:
                            | T
                            | {
                                type?: T;
                                page?: T;
                                post?: T;
                                label?: T;
                                url?: T;
                                image?: T;
                                newTab?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              image1?: T;
              image2?: T;
              id?: T;
              blockName?: T;
            };
        heroscreen?:
          | T
          | {
              hero_image?: T;
              id?: T;
              blockName?: T;
            };
        parallax?:
          | T
          | {
              parallax_image?: T;
              parallax_speed?: T;
              id?: T;
              blockName?: T;
            };
        'html-content'?:
          | T
          | {
              htmlCode?: T;
              id?: T;
              blockName?: T;
            };
      };
  coverImage?: T;
  config?:
    | T
    | {
        published?: T;
        createdBy?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  menuId?: T;
  items?:
    | T
    | {
        type?: T;
        page?: T;
        post?: T;
        label?: T;
        url?: T;
        image?: T;
        newTab?: T;
        children?:
          | T
          | {
              type?: T;
              page?: T;
              post?: T;
              label?: T;
              url?: T;
              image?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  themeName?: T;
  zip?: T;
  themeData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  formType?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              label?: T;
              placeholder?: T;
              min?: T;
              max?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice".
 */
export interface LegalNotice {
  id: number;
  editeur: {
    identite: string;
    capital?: string | null;
    coordonnees?: {
      adresse?: string | null;
      email?: string | null;
      telephone?: string | null;
    };
  };
  concepteur: {
    nom: string;
    site?: string | null;
  };
  hebergeur: {
    nom: string;
    adresse?: string | null;
    site?: string | null;
  };
  other?: {
    proprieteIntellectuelle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confidentiality".
 */
export interface Confidentiality {
  id: number;
  identity: {
    id_name: string;
    id_adress: string;
    id_email: string;
    id_tel?: string | null;
  };
  personal_data?: {
    data_collected?:
      | {
          data_collect?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cgv".
 */
export interface Cgv {
  id: number;
  user_data: {
    user_name: string;
    user_adress: string;
    user_email: string;
    user_siret: string;
  };
  services_data?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  payments_data: {
    payment: {
      payment_item: string;
      id?: string | null;
    }[];
    prepayment?: boolean | null;
    payment_place?: boolean | null;
  };
  cancel_conditions: {
    cancel_delay: string;
    cancel_fees: string;
    special_cancel_conditions?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization".
 */
export interface Customization {
  id: number;
  identity?: {
    site_title?: string | null;
    homepage?: (number | null) | Page;
    site_logo?: (number | null) | Media;
    site_favicon?: (number | null) | Media;
  };
  typography?: {
    body?: {
      body_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      body_size?: string | null;
      body_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title1?: {
      title1_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title1_size?: string | null;
      title1_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title2?: {
      title2_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title2_size?: string | null;
      title2_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title3?: {
      title3_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title3_size?: string | null;
      title3_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title4?: {
      title4_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title4_size?: string | null;
      title4_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title5?: {
      title5_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title5_size?: string | null;
      title5_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
    title6?: {
      title6_font?: ('lato' | 'montserrat' | 'raleway' | 'roboto') | null;
      title6_size?: string | null;
      title6_weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800') | null;
    };
  };
  custom_css?: {
    custom_css_block?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice_select".
 */
export interface LegalNoticeSelect<T extends boolean = true> {
  editeur?:
    | T
    | {
        identite?: T;
        capital?: T;
        coordonnees?:
          | T
          | {
              adresse?: T;
              email?: T;
              telephone?: T;
            };
      };
  concepteur?:
    | T
    | {
        nom?: T;
        site?: T;
      };
  hebergeur?:
    | T
    | {
        nom?: T;
        adresse?: T;
        site?: T;
      };
  other?:
    | T
    | {
        proprieteIntellectuelle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confidentiality_select".
 */
export interface ConfidentialitySelect<T extends boolean = true> {
  identity?:
    | T
    | {
        id_name?: T;
        id_adress?: T;
        id_email?: T;
        id_tel?: T;
      };
  personal_data?:
    | T
    | {
        data_collected?:
          | T
          | {
              data_collect?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cgv_select".
 */
export interface CgvSelect<T extends boolean = true> {
  user_data?:
    | T
    | {
        user_name?: T;
        user_adress?: T;
        user_email?: T;
        user_siret?: T;
      };
  services_data?:
    | T
    | {
        service?: T;
        id?: T;
      };
  payments_data?:
    | T
    | {
        payment?:
          | T
          | {
              payment_item?: T;
              id?: T;
            };
        prepayment?: T;
        payment_place?: T;
      };
  cancel_conditions?:
    | T
    | {
        cancel_delay?: T;
        cancel_fees?: T;
        special_cancel_conditions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization_select".
 */
export interface CustomizationSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        site_title?: T;
        homepage?: T;
        site_logo?: T;
        site_favicon?: T;
      };
  typography?:
    | T
    | {
        body?:
          | T
          | {
              body_font?: T;
              body_size?: T;
              body_weight?: T;
            };
        title1?:
          | T
          | {
              title1_font?: T;
              title1_size?: T;
              title1_weight?: T;
            };
        title2?:
          | T
          | {
              title2_font?: T;
              title2_size?: T;
              title2_weight?: T;
            };
        title3?:
          | T
          | {
              title3_font?: T;
              title3_size?: T;
              title3_weight?: T;
            };
        title4?:
          | T
          | {
              title4_font?: T;
              title4_size?: T;
              title4_weight?: T;
            };
        title5?:
          | T
          | {
              title5_font?: T;
              title5_size?: T;
              title5_weight?: T;
            };
        title6?:
          | T
          | {
              title6_font?: T;
              title6_size?: T;
              title6_weight?: T;
            };
      };
  custom_css?:
    | T
    | {
        custom_css_block?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}